version: '2.3'
services:
  postgres:
    image: "postgres"
    environment:
      - "POSTGRES_PASSWORD=secret"
    ports:
      - "5432:5432"
  rabbitmq:
    image: masstransit/rabbitmq:latest
    ports:
      - "5672:5672"
      - "15672:15672"
